from django.core.management.base import BaseCommand
from app1.models import Question  # Replace 'yourapp' with your actual app name

class Command(BaseCommand):
    help = 'Populate the database with Genesis Questions'
    
    def handle(self, *args, **kwargs):
        Questions = [
            # (Question_text, choice1, choice2, choice3, choice4, answer, book, category)
            ("Who is the first man created by God?", "Adam", "Noah", "Abraham", "Moses", 0, "Genesis", "Old"),
            ("Who was Adam's wife?", "Eve", "Sarah", "Leah", "Rebecca", 0, "Genesis", "Old"),
            ("What did God create on the first day?", "Light", "Land", "Plants", "Animals", 0, "Genesis", "Old"),
            ("Who built the Ark?", "Moses", "Noah", "Abraham", "Jacob", 1, "Genesis", "Old"),
            ("What sign did God give Noah as a promise not to flood the earth again?", "Star", "Rainbow", "Cloud", "Dove", 1, "Genesis", "Old"),
            ("Who was the first murderer in the Bible?", "Cain", "Abel", "Seth", "Lamech", 0, "Genesis", "Old"),
            ("How many sons did Jacob have?", "10", "12", "14", "8", 1, "Genesis", "Old"),
            ("Which son of Abraham was almost sacrificed?", "Ishmael", "Isaac", "Jacob", "Esau", 1, "Genesis", "Old"),
            ("Who was the twin brother of Jacob?", "Esau", "Joseph", "Benjamin", "Reuben", 0, "Genesis", "Old"),
            ("What did God change Jacob's name to?", "Israel", "Isaac", "Judah", "Joseph", 0, "Genesis", "Old"),
            ("What land did Abraham travel to after leaving Ur?", "Canaan", "Egypt", "Babylon", "Philistia", 0, "Genesis", "Old"),
            ("Who was Abraham's first son?", "Isaac", "Ishmael", "Jacob", "Joseph", 1, "Genesis", "Old"),
            ("What was the name of Isaac's wife?", "Rebekah", "Leah", "Rachel", "Sarah", 0, "Genesis", "Old"),
            ("How old was Noah when the flood began?", "600", "500", "400", "300", 0, "Genesis", "Old"),
            ("What does 'Genesis' mean?", "Creation", "Beginning", "History", "Family", 1, "Genesis", "Old"),
            ("Who was sold into slavery by his brothers?", "Joseph", "Benjamin", "Reuben", "Judah", 0, "Genesis", "Old"),
            ("What was the first thing that God created?", "Light", "Earth", "Sun", "Animals", 0, "Genesis", "Old"),
            ("Which city did God destroy due to its wickedness?", "Jericho", "Sodom", "Babylon", "Nineveh", 1, "Genesis", "Old"),
            ("Who was the father of many nations?", "Isaac", "Abraham", "Jacob", "Joseph", 1, "Genesis", "Old"),
            ("What was the name of Abraham's nephew?", "Lot", "Nahor", "Haran", "Ishmael", 0, "Genesis", "Old"),
            ("What did God use to create man?", "Dust", "Water", "Fire", "Spirit", 0, "Genesis", "Old"),
            ("How many animals of each kind did Noah take on the Ark?", "One", "Two", "Three", "Four", 1, "Genesis", "Old"),
            ("What did Jacob dream about?", "A ladder to heaven", "A burning bush", "A chariot of fire", "A great flood", 0, "Genesis", "Old"),
            ("Which of Jacob's sons was the favorite?", "Reuben", "Joseph", "Levi", "Judah", 1, "Genesis", "Old"),
            ("What was the name of Sarah's maid?", "Hagar", "Bilhah", "Zilpah", "Leah", 0, "Genesis", "Old"),
            ("Who was the first to be circumcised?", "Abraham", "Isaac", "Jacob", "Joseph", 0, "Genesis", "Old"),
            ("What was the name of Isaac's father?", "Abraham", "Jacob", "Noah", "Joseph", 0, "Genesis", "Old"),
            ("Who tricked Isaac into giving him the blessing?", "Jacob", "Esau", "Joseph", "Laban", 0, "Genesis", "Old"),
            ("What did Joseph interpret for Pharaoh?", "Dreams", "Visions", "Prophecies", "Signs", 0, "Genesis", "Old"),
            ("Who was the mother of Esau and Jacob?", "Rebekah", "Leah", "Sarah", "Rachel", 0, "Genesis", "Old"),
            ("What was the name of the place where God confused the language of the people?", "Babel", "Egypt", "Canaan", "Babylon", 0, "Genesis", "Old"),
            ("Who was the first king of Israel?", "Saul", "David", "Solomon", "Samuel", 0, "1 Samuel", "Old"),
            ("How long did Jacob work for Laban to marry Rachel?", "7 years", "14 years", "21 years", "10 years", 1, "Genesis", "Old"),
            ("What were the names of Jacob's two wives?", "Leah and Rachel", "Sarah and Hagar", "Rebekah and Leah", "Rachel and Zilpah", 0, "Genesis", "Old"),
            ("Who did God tell to sacrifice his son?", "Abraham", "Isaac", "Jacob", "Joseph", 0, "Genesis", "Old"),
            ("What was the name of Isaac's servant who found Rebekah?", "Eliezer", "Laban", "Judah", "Joseph", 0, "Genesis", "Old"),
            ("What did God promise Abraham?", "Many descendants", "Wealth", "Long life", "Wisdom", 0, "Genesis", "Old"),
            ("Who was the first child of Adam and Eve?", "Abel", "Cain", "Seth", "Enoch", 1, "Genesis", "Old"),
            ("What animal did Jacob use to breed spotted and speckled offspring?", "Goats", "Sheep", "Cattle", "Donkeys", 0, "Genesis", "Old"),
            ("What did God tell Noah to build?", "A tower", "An altar", "An ark", "A city", 2, "Genesis", "Old"),
            ("How many days and nights did it rain during the flood?", "30", "40", "50", "60", 1, "Genesis", "Old"),
            ("Who was Joseph's mother?", "Leah", "Rachel", "Rebekah", "Zilpah", 1, "Genesis", "Old"),
            ("Who was the king of Egypt during Joseph's time?", "Pharaoh", "Nebuchadnezzar", "Darius", "Cyrus", 0, "Genesis", "Old"),
            ("What did Jacob see in his dream?", "A ladder", "A tree", "A river", "A mountain", 0, "Genesis", "Old"),
            ("How long did Abraham live?", "175", "150", "120", "200", 0, "Genesis", "Old"),
            ("What did Lot's wife turn into?", "A rock", "A tree", "A pillar of salt", "A statue", 2, "Genesis", "Old"),
            ("Who did Jacob wrestle with all night?", "An angel", "A demon", "Esau", "Laban", 0, "Genesis", "Old"),
            ("What was the first plague in Egypt?", "Frogs", "Blood", "Locusts", "Hail", 1, "Exodus", "Old"),
            ("Who was the father of Joseph?", "Isaac", "Jacob", "Abraham", "Laban", 1, "Genesis", "Old"),
            ("Who sold Joseph into slavery?", "His brothers", "The Midianites", "Potiphar", "Pharaoh", 0, "Genesis", "Old"),
          
    ("Who baptized Jesus?", "John the Baptist", "Peter", "James", "Andrew", 0, "Matthew", "New"),
    ("What did Jesus turn water into?", "Wine", "Oil", "Milk", "Vinegar", 0, "Matthew", "New"),
    ("What is the first miracle of Jesus in Matthew?", "Healing a leper", "Turning water into wine", "Feeding the 5000", "Walking on water", 1, "Matthew", "New"),
    ("Which sermon is known as the Sermon on the Mount?", "Matthew 5-7", "Matthew 3", "Matthew 10", "Matthew 12", 0, "Matthew", "New"),
    ("What did Jesus say was the greatest commandment?", "Love God", "Do not steal", "Honor your parents", "Love your neighbor", 0, "Matthew", "New"),
    ("How many disciples did Jesus choose?", "12", "10", "7", "15", 0, "Matthew", "New"),
    ("What did Jesus feed to the 5000?", "Bread and fish", "Bread and meat", "Fish and fruit", "Rice and beans", 0, "Matthew", "New"),
    ("Who denied Jesus three times?", "John", "Peter", "Judas", "Thomas", 1, "Matthew", "New"),
    ("What was the profession of Matthew before following Jesus?", "Fisherman", "Tax collector", "Zealot", "Pharisee", 1, "Matthew", "New"),
    ("What did Jesus say about worry?", "Worry shows faith", "Do not worry about tomorrow", "Worry is sin", "Worry is good for you", 1, "Matthew", "New"),
    ("What did Jesus say the kingdom of heaven is like?", "A treasure", "A pearl", "A mustard seed", "All of the above", 3, "Matthew", "New"),
    ("Who is known as the 'rock' of the church?", "Matthew", "John", "James", "Peter", 3, "Matthew", "New"),
    ("What parable teaches about forgiveness?", "The Good Samaritan", "The Lost Sheep", "The Unforgiving Servant", "The Sower", 2, "Matthew", "New"),
    ("Who visited Jesus after his birth?", "Angels", "Wise Men", "Shepherds", "Kings", 1, "Matthew", "New"),
    ("What was the sign of Jonah?", "A great storm", "Three days in the belly of a fish", "A dove", "A whale", 1, "Matthew", "New"),
    ("What did Jesus say about the narrow gate?", "It is wide", "Few find it", "Everyone will enter", "It is easy to find", 1, "Matthew", "New"),
    ("What did Jesus say to do when you are angry?", "Ignore it", "Speak out", "Reconcile with your brother", "Let it go", 2, "Matthew", "New"),
    ("Who betrayed Jesus for thirty pieces of silver?", "Peter", "John", "Judas Iscariot", "Thomas", 2, "Matthew", "New"),
    ("What did Jesus do in the temple?", "Preached", "Healed the sick", "Turned over the tables", "Washed feet", 2, "Matthew", "New"),
    ("What did Jesus say at the Last Supper?", "This is my body", "Remember me", "This is my blood", "All of the above", 3, "Matthew", "New"),
    ("How did Jesus enter Jerusalem?", "On a horse", "In a chariot", "On foot", "Riding on a donkey", 3, "Matthew", "New"),
    ("Who was the Roman governor who sentenced Jesus to death?", "Herod", "Caesar", "Pontius Pilate", "Tiberius", 2, "Matthew", "New"),
    ("What did Jesus say about the Sabbath?", "It is a holy day", "It was made for man", "It is a burden", "Man was made for it", 1, "Matthew", "New"),
    ("What is the Lord's Prayer?", "Hail Mary...", "The Apostles' Creed", "Our Father who art in heaven...", "The Shema", 2, "Matthew", "New"),
    ("What did Jesus do immediately after his baptism?", "Started preaching", "Went into the wilderness", "Gathered disciples", "Performed miracles", 1, "Matthew", "New"),
    ("Who was Jesus' earthly father?", "David", "Abraham", "Zacharias", "Joseph", 3, "Matthew", "New"),
    ("What city is Jesus from?", "Capernaum", "Bethlehem", "Nazareth", "Jerusalem", 2, "Matthew", "New"),
    ("What did Jesus say to the storm?", "Be quiet", "Calm down", "Peace, be still", "Go away", 2, "Matthew", "New"),
    ("What is the golden rule?", "Do to others what you would have them do to you", "Love your neighbor", "Honor your parents", "Pray without ceasing", 0, "Matthew", "New"),
    ("Who did Jesus raise from the dead?", "The widow's son", "Jairus' daughter", "Lazarus", "All of the above", 3, "Matthew", "New"),
    ("What was the name of the garden where Jesus prayed?", "Bethany", "Gethsemane", "Eden", "Golgotha", 1, "Matthew", "New"),
    ("What did Jesus say is the way to eternal life?", "Do good deeds", "Follow me", "Believe in me", "All of the above", 2, "Matthew", "New"),
    ("What should you do if someone strikes you on one cheek?", "Turn the other cheek", "Run away", "Fight back", "Ignore it", 0, "Matthew", "New"),
    ("What did Jesus say about the rich?", "They will be judged", "It is hard for them to enter the kingdom", "They will inherit the earth", "They will be rewarded", 1, "Matthew", "New"),
    ("What did the disciples do during the storm?", "Slept", "Cried out in fear", "Fought the wind", "Prayed", 1, "Matthew", "New"),
    ("What is the significance of the number '40' in Matthew?", "Days of rain", "Days of fasting", "Years of wandering", "All of the above", 3, "Matthew", "New"),
    ("Who did the Pharisees send to trap Jesus?", "Disciples", "Spies", "Soldiers", "Tax collectors", 1, "Matthew", "New"),
    ("What was the name of the mountain where Jesus was transfigured?", "Mount Sinai", "Mount Tabor", "Mount Olives", "Mount Hermon", 3, "Matthew", "New"),
    ("What did Jesus say to the woman at the well?", "I can give you living water", "You are a sinner", "Where is your husband?", "I know you", 0, "Matthew", "New"),
    ("What is the first beatitude?", "Blessed are those who mourn", "Blessed are the merciful", "Blessed are the poor in spirit", "Blessed are the meek", 2, "Matthew", "New"),
    ("What did the angels say at Jesus' birth?", "Peace on earth", "Fear not", "All of the above", "Glory to God in the highest", 2, "Matthew", "New"),
    ("How many parables are in Matthew?", "10", "Over 20", "5", "15", 1, "Matthew", "New"),
    ("What is the parable of the lost sheep about?", "Forgiving debts", "Helping others", "Finding treasure", "God's love for sinners", 3, "Matthew", "New"),
    ("What did Jesus say to the woman caught in adultery?", "You are forgiven", "Go and sin no more", "What do you want?", "Repent", 1, "Matthew", "New"),
    ("What is the significance of the fig tree?", "It is a sign of judgment", "It is a symbol of peace", "It represents Israel", "It bears fruit", 2, "Matthew", "New"),
    ("What did Jesus say about prayer?", "Pray in secret", "Pray loudly", "Pray for power", "Pray for wealth", 0, "Matthew", "New"),
    ("What did Jesus do before choosing his disciples?", "Fast", "Studied the law", "Prayed all night", "Preached", 2, "Matthew", "New"),
    ("Who were the first to see the resurrected Jesus?", "Roman soldiers", "Women", "Angels", "Disciples", 1, "Matthew", "New"),
    ("What did Jesus say about those who mourn?", "They will be judged", "They will be comforted", "They will be ignored", "They will be happy", 1, "Matthew", "New"),
    ("What did Jesus use to describe himself?", "The Light of the World", "The Good Shepherd", "The Bread of Life", "All of the above", 3, "Matthew", "New"),
]
        

       
        for eachquestion in Questions:
            print(f"Creating Question: {eachquestion[0]}, Book: {eachquestion[6]}, Category: {eachquestion[7]}")  # Debug output
            Question.objects.create(
              Question_text=eachquestion[0],
              choice1=eachquestion[1],
              choice2=eachquestion[2],
              choice3=eachquestion[3],
              choice4=eachquestion[4],
              answer=eachquestion[5],
              book=eachquestion[6],
              category=eachquestion[7]
             )
    
        self.stdout.write(self.style.SUCCESS('Questions added successfully!'))