# Generated by Django 5.1.4 on 2025-01-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_questiondb_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondb',
            name='question_text',
            field=models.TextField(),
        ),
    ]
