# Generated by Django 5.1.4 on 2025-01-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_questiondb_question_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questiondb',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='questiondb',
            name='answer',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='questiondb',
            name='category',
            field=models.CharField(blank=True, choices=[('Genesis', 'Genesis'), ('Exodus', 'Exodus')], max_length=50),
        ),
    ]
