# Generated by Django 5.1.4 on 2025-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_questiondb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondb',
            name='category',
            field=models.CharField(blank=True, choices=[('Old', 'Old Testament'), ('New', 'New Testament')], max_length=50),
        ),
    ]
