# Generated by Django 5.1.4 on 2025-01-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_questiondb_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionDB',
            new_name='Question',
        ),
    ]
