# Generated by Django 5.1.4 on 2025-01-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_questiondb_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='Question_text',
        ),
    ]
