# Generated by Django 5.1.4 on 2025-01-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_rename_question_text_question_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Old Testament', 'Old Testament'), ('New Testament', 'New Testament')], max_length=50),
        ),
    ]
