# Generated by Django 5.1.4 on 2025-01-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_question_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='correct_answer',
        ),
    ]
